decimal=int(input("enter a decimal number:"))
print("the conversion of decimal number ",decimal,"is :")
print(bin(decimal),"in binary")
print(oct(decimal),"in octal")
print(hex(decimal),"in hexadecimal")